name: calc
description: "A new Flutter package project."
version: 0.0.2-calc.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  packageone:
    git: 
      url: git@github.com:rahul-2901/melos-test.git
      path: packages/packageone
      ref: packageone-v0.1.0-calc.0

  packagetwo:
    git: 
      url: git@github.com:rahul-2901/melos-test.git
      path: packages/packagetwo
      ref: packagetwo-v0.1.0-calc.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: