name: packagetwo
description: "A new Flutter package project."
version: 0.1.0-package-update.0
homepage:
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  packageone:
    git:
      url: git@github.com:rahul-2901/melos-test.git
      path: packages/packageone
      ref: packagetwo-v0.1.0-package-update.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: